// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqw4otmCq6kq9n029d3NPgCkFzih1NY_c',
    appId: '1:869693854342:web:ca1d44fb2560c0cbcbb707',
    messagingSenderId: '869693854342',
    projectId: 'ecomercelearningproject',
    authDomain: 'ecomercelearningproject.firebaseapp.com',
    storageBucket: 'ecomercelearningproject.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPW1xYtyZ0joaoTwrTsY7tDG3RHz6fV3w',
    appId: '1:869693854342:android:5ab9d67b4ddd858fcbb707',
    messagingSenderId: '869693854342',
    projectId: 'ecomercelearningproject',
    storageBucket: 'ecomercelearningproject.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsSsOKgi85nPxbn9MevK84LvZ__yt-QM4',
    appId: '1:869693854342:ios:a3922e9d8112946ccbb707',
    messagingSenderId: '869693854342',
    projectId: 'ecomercelearningproject',
    storageBucket: 'ecomercelearningproject.firebasestorage.app',
    iosBundleId: 'com.example.sStore',
  );
}
